FROM python:3.12.10-alpine AS builder
WORKDIR /app
COPY requirements.txt .
RUN apk add --no-cache build-base && pip install --prefix=/install -r requirements.txt

FROM python:3.12.10-alpine AS runtime
WORKDIR /app
COPY --from=builder /install /usr/local
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
