version: '3.8'
services:
  app.py:
   build: .
   ports: 
    - "5000:5000"
   environment:
     - FLASK_ENV=development
     - MYSQL_HOST=mysql 
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     - MYSQL_DATABASE=flask_db
   depends_on:
     - mysql
     - redis
   networks:
    - app-network
  mysql:
   image: mysql:5.7.43
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=flask_db
   ports:
     - "3306"
   volumes:
     - mysql_data:/usr/src/mysql-bd
   networks:
     - app-network
  redis:
   image: redis:8.0-rc1
   ports:
     - "6379"
   volumes:
     - redis_data:/usr/src/redis-db
   networks:
     - app-network
networks:
   app-network:
volumes:
  mysql_data:
  redis_data:
    



  