services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000"
    networks:
      - backend

  db:
    image: postgres:13.9-alpine3.16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:8.0-rc1-alpine3.21
    container_name: redis_cache
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine-perl
    container_name: nginx_proxy
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
